version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - net_wp

  wordpress_cli:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - net_wp
    entrypoint: bash /entrypoint.sh

  db:
    image: mysql:8.1.0-oracle
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

    env_file: .env
    networks:
      - net_wp
      - net_pma

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    env_file: .env
    ports:
      - 8081:80
    networks:
      - net_pma

networks:
  net_wp:
  net_pma:
