version: '3.1'

services:

  wordpress:
    image: wordpress
    depends_on:
      - db
    restart: always
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - net_wp
      - net_cloudflare
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run --token ${TOKEN}"
    networks:
      - net_cloudflare

  wordpress_cli:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - net_wp
    entrypoint: bash /entrypoint.sh

  db:
    image: mysql:8.1.0-oracle
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    networks:
      - net_wp
      - net_pma

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    depends_on:
      - db
    restart: always
    env_file: .env
    networks:
      - net_pma
      - net_cloudflare

networks:
  net_wp:
  net_pma:
  net_cloudflare:
