- hosts: Deploy
  become: true
  tasks:
  - name: Upload Playbook
    tags: UploadPlaybook
    copy:
      src: ./deploy/aws.yaml
      dest: /root/deploy.yaml
      owner: root
      group: root
      mode: '0640'
  - name: Upload env
    tags: UploadEnv
    copy:
      src: ./deploy/.env
      dest: /root/.env
      owner: root
      group: root
      mode: '0640'
  - name: Upload scipt
    tags: UploadScript
    copy:
      src: ./deploy/run_playbook.sh
      dest: /root/run_playbook.sh
      owner: root
      group: root
      mode: '0777'
  - name: Deploy instance
    tags: Deploy
    command: 'sudo su - -c "sh /root/run_playbook.sh"'
